# Generated by Django 5.2.6 on 2025-09-23 13:46

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_test_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    User.objects.create(
        username='admin',
        first_name='Oleg',
        last_name='Dixon',
        password=make_password('adminpass'),
        is_staff=True,
        is_superuser=True
    )
    
    User.objects.create(
        username='Papa', 
        first_name='Папа',
        last_name='Дюкарев',
        password=make_password('testpass')
    )
    
    User.objects.create(
        username='Maria',
        first_name='Мария', 
        last_name='Дюкарева',
        password=make_password('testpass')
    )

def delete_test_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username__in=['admin', 'Papa', 'Maria']).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]
    
    operations = [
        migrations.RunPython(create_test_users, delete_test_users),
    ]