# Generated by Django 5.2.6 on 2025-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название статуса'),
        ),
    ]
